DESCRIPTION = "hector_geotiff_plugins contains plugins that extend geotiff maps generated by hector_geotiff."
AUTHOR = "Stefan Kohlbrecher"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=13;endline=13;md5=d566ef916e9dedc494f5f793a6690ba5"

DEPENDS = "hector-geotiff hector-nav-msgs hector-geotiff hector-nav-msgs"

RDEPENDS_${PN} = "hector-geotiff hector-nav-msgs"

SRC_URI = "https://github.com/tu-darmstadt-ros-pkg-gbp/hector_slam-release/archive/release/melodic/hector_geotiff_plugins/0.4.0-1.tar.gz;downloadfilename=${ROS_BPN}-${PV}.tar.gz"
SRC_URI[md5sum] = "b3affa641c2f0fd24b5d453494671661"
SRC_URI[sha256sum] = "a99af08c43131cca5c839e5680e3957315ecff893934b89d1b9da98bb8971ad0"

ROS_SPN = "hector_slam"
S = "${WORKDIR}/hector_slam-release-release-melodic-hector_geotiff_plugins-0.4.0-1"

inherit catkin
